server:
  port: 8080

spring:
  jackson:
    property-naming-strategy : SNAKE_CASE

---

spring:
  profiles:
    active: local
    include: oauth
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: smith1380!

logging:
    level:
      root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---

spring:
  profiles:
    active: production