server:
  port: 8080

---

spring:
  profiles:
    active: local
    include: oauth
  jpa:
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

---

spring:
  profiles:
    active: production